import { Navigate } from "react-router-dom";
import AuthService from "./AuthService";
import LoginForm from "./LoginForm";
import MovingImage from "./movingimage";
import "./Stylesheets/loginpage.css";
import "spectre.css";

function LoginPage() {
  const isLoggedIn = AuthService.isLoggedIn();
  if (isLoggedIn) {
    return <Navigate to="/" />;
  } else {
    return (
      
      <div className="page-wrapper">
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage /><MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage /><MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage /><MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <MovingImage />
        <LoginForm />
      </div>
    );
  }
}

export default LoginPage;
